version = 0.1
[default.deploy.parameters]
stack_name = "CybersecurityPolitoBot-Telegram"
resolve_s3 = true
s3_prefix = "CybersecurityPolitoBot-Telegram"
region = "eu-west-1"
image_repositories = []
capabilities = "CAPABILITY_IAM"